### ISSUE TITLE
right to left layer name in sidebar-v2

### ISSUE THREAD

**Issue by Alish84** [walkermatt/ol-layerswitcher#285] opened 2020-04-01 09:55 UTC
Hi
I was going to use ol3-layerswitcher with sidebar-v2. I have encountered a problem in the layer name and group layer. I can't change text direction to "right to left" for the language differing from En, like Persian.
![Untitled](https://user-images.githubusercontent.com/46603950/78124235-a4c15600-7424-11ea-91e2-5ff1511cd73d.png)

**Comment by walkermatt** [comment] 2020-04-10 20:49
Duplicate of #286

**Closed by walkermatt** 2020-04-10 20:49 UTC
